# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

sudo: false

compiler:
  - gcc
  - clang

branches:
  only:
    - master

env:
  global:
    - OMP_NUM_THREADS=4

before_script:
  - ./autogen.sh

script:
  - ./configure --enable-examples CXXFLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2"
  - make
  - make install
  - make dist
  - make distcheck
