branches:
  only:
  - master

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

before_build:
  "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /%platform%"

build_script:
  - nmake /f Makefile.msvc

test_script:
  - nmake /f Makefile.msvc check
